-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

USE ecommerce_db;

CREATE TABLE category
 (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  category_name VARCHAR(30) NOT NULL,
  salary DECIMAL,
);